[supervisord]
nodaemon=true

[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"

[program:cron]
command = cron -f -L 15
autostart=true
autorestart=true

[program:service-runner]
command =/bin/bash -c "/home/pi/emonpi/service-runner"
autostart=false
autorestart=false
startretries=0
