[supervisord]
nodaemon=true

[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"

[program:service-runner]
command =/bin/bash -c "/home/pi/emonpi/service-runner"
